import { normalizeVendorCategoryMainSlugs } from "@/lib/catalog/vendor-category-normalize";

/** Safe new-style slugs: category prefix + short id suffix (no brand/handle). */
const SAFE_VENDOR_SLUG_RE =
  /^(?:postavshik(?:-(?:zhenskoy-odezhdy|muzhskoy-odezhdy|detskoy-odezhdy|obuvi|sumok|tkani|aksessuarov|tekstilya|sporta|belya))?|vendor)-[a-z0-9]{4,6}$/;

export type VendorProfileRobotsPolicy = "index,follow" | "noindex,follow";

/** True for category-prefix slugs generated by `buildVendorSlug` (not legacy brand slugs). */
export function isSafeVendorPublicSlug(slug: string): boolean {
  const normalized = slug.trim().toLowerCase();
  if (!normalized) return false;
  return SAFE_VENDOR_SLUG_RE.test(normalized);
}

export function vendorProfileRobotsPolicy(slug: string): VendorProfileRobotsPolicy {
  return isSafeVendorPublicSlug(slug) ? "index,follow" : "noindex,follow";
}

/** Stable public listing number derived from vendor UUID (not sequential DB id). */
export function vendorPublicListingNumber(vendorId: string): string {
  const tail = vendorId.replace(/-/g, "").slice(-4);
  const n = Number.parseInt(tail, 16);
  if (!Number.isFinite(n)) return "0000";
  return String(n % 10000).padStart(4, "0");
}

export function primaryVendorMainCategoryId(
  categories: string[] | null | undefined,
): string | undefined {
  return normalizeVendorCategoryMainSlugs(categories)[0];
}
