import { normalizeVendorCategoryMainSlugs } from "@/lib/catalog/vendor-category-normalize";

/** Safe new-style slugs: category prefix + short id suffix (no brand/handle). */
const SAFE_VENDOR_SLUG_RE =
  /^(?:postavshik(?:-(?:zhenskoy-odezhdy|muzhskoy-odezhdy|detskoy-odezhdy|obuvi|sumok|tkani|aksessuarov|tekstilya|sporta|belya))?|vendor)-[a-z0-9]{4,6}$/;

export type VendorProfileRobotsPolicy = "index,follow" | "noindex,follow";

/** True for category-prefix slugs generated by `buildVendorSlug` (not legacy brand slugs). */
export function isSafeVendorPublicSlug(slug: string): boolean {
  const normalized = slug.trim().toLowerCase();
  if (!normalized) return false;
  return SAFE_VENDOR_SLUG_RE.test(normalized);
}

export function vendorSuppliersSeoPath(seoSlug: string): string {
  return `/suppliers/${seoSlug.trim()}`;
}

/** Catalog profile pages are never indexed; SEO lives on `/suppliers/`. */
export function vendorCatalogRobotsPolicy(): VendorProfileRobotsPolicy {
  return "noindex,follow";
}

/** Suppliers SEO landing — index when site is indexable. */
export function vendorSuppliersSeoRobotsPolicy(): VendorProfileRobotsPolicy {
  return "index,follow";
}

/** Stable public listing number derived from vendor UUID (not sequential DB id). */
export function vendorPublicListingNumber(vendorId: string): string {
  const tail = vendorId.replace(/-/g, "").slice(-4);
  const n = Number.parseInt(tail, 16);
  if (!Number.isFinite(n)) return "0000";
  return String(n % 10000).padStart(4, "0");
}

export function vendorPublicStoreLabel(
  storeName: string | null | undefined,
  fallbackLabel: string,
): string {
  const normalized = storeName?.replace(/\s+/g, " ").trim();
  return normalized ? normalized.slice(0, 120) : fallbackLabel;
}

type VendorSeoTranslator = (
  key: string,
  values?: Record<string, string>,
) => string;

export function buildVendorSuppliersSeoCopy(opts: {
  t: VendorSeoTranslator;
  storeLabel: string;
  categoryPhrase: string | null;
}) {
  const { t, storeLabel, categoryPhrase } = opts;
  return {
    title: categoryPhrase
      ? t("publicSeo.suppliersMetaTitleWithCategory", {
          store: storeLabel,
          category: categoryPhrase,
        })
      : t("publicSeo.suppliersMetaTitle", { store: storeLabel }),
    description: categoryPhrase
      ? t("publicSeo.suppliersMetaDescriptionWithCategory", {
          store: storeLabel,
          category: categoryPhrase,
        })
      : t("publicSeo.suppliersMetaDescription", { store: storeLabel }),
  };
}

export function primaryVendorMainCategoryId(
  categories: string[] | null | undefined,
): string | undefined {
  return normalizeVendorCategoryMainSlugs(categories)[0];
}
